### ISSUE TITLE
noob question xD

### ISSUE THREAD

**Issue by P5-2005** [matteyeux/ida-iboot-loader#2]
hello,
i wonder how to find base address per iboot file?, what im trying, always i get  this !: 
[i] bootloader : RELEASE
[!] Failed to find base address, it's now set to 0x0
[+] Rebasing to address 0x0

IDA 7.6 on windows

thanks

**Comment by matteyeux** [comment]
Can you please specify the iOS version and the device of this iBoot

**Comment by P5-2005** [comment]
> Can you please specify the iOS version and the device of this iBoot

i tried random like A11 iOS 14.8, A9 iOS 14.8, WatchOS 6.3, well what i have decrypted on my test machine, not specific one, this why i asked first place

**Comment by matteyeux** [comment]
- Apple Watch S2 is a 32 bits device. It is not supported
- For A11 and A9 it should work. I will test again as soon as possible. How are you decrypting it? Are you sure it's correctly decrypted ?

**Comment by P5-2005** [comment]
> * Apple Watch S2 is a 32 bits device. It is not supported
> 
>     * For A11 and A9 it should work. I will test again as soon as possible. How are you decrypting it? Are you sure it's correctly decrypted ?

oh thanks for watch s2,
i used autodecrypt, img4 too,
